name: Tests

on: [ push,workflow_dispatch,workflow_call,pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-13, macos-14, windows-2019 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Compile all
        run: mvn install -"DskipTests" -"Dgpg.skip"

      - name: Run Cell tests
        run: |
          cd cell
          mvn test

      - name: Run Func tests
        run: |
          cd func
          mvn test

      - name: Run Fift tests
        run: |
          cd fift
          mvn test

      - name: Run Tolk tests
        run: |
          cd tolk
          mvn test

      - name: Run LiteClient tests
        run: |
          cd liteclient
          mvn test -Dtest=LiteClientTest#testLastExecuted

      - name: Run Address tests
        run: |
          cd address
          mvn test

      - name: Run Cell tests
        run: |
          cd cell
          mvn test

      - name: Run tonlib - testTonlibGetTxsByAddress
        run: |
          cd tonlib
          mvn test -Dtest=TestTonlibJsonTestnet#testTonlibGetTxsByAddress

      - name: Run tonlib - testTonlibRunMethodParticipantsList
        run: |
          cd tonlib
          mvn test -Dtest=TestTonlibJsonTestnet#testTonlibRunMethodParticipantsList

      - name: Run Utils tests
        run: |
          cd utils
          mvn test

      - name: Run Disassembler tests
        run: |
          cd disassembler
          mvn test

      - name: Run BitString tests
        run: |
          cd bitstring
          mvn test